# Generated by Django 2.2 on 2023-10-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_rows', models.IntegerField()),
                ('num_cols', models.IntegerField()),
                ('cell_width', models.FloatField()),
                ('cell_height', models.FloatField()),
            ],
        ),
    ]
