# Generated by Django 2.2 on 2023-10-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableconfig',
            name='merge_cells',
        ),
    ]
